name: bouldering_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router:
  flutter_riverpod: ^2.6.0
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  auto_route: ^6.3.0
  intl: ^0.19.0
  url_launcher: ^6.1.6
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_functions: ^5.2.0
  http: ^1.2.2
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  auto_route_generator: ^6.2.0
  build_runner: ^2.3.3
flutter:
  assets:
    - lib/view/assets/app_main_icon.svg
    - lib/view/assets/rock_selected.svg
    - lib/view/assets/rock_unselected.svg
    - lib/view/assets/map_image.png
    - lib/view/assets/date_range.svg
    - lib/view/assets/home_gim_icon.svg
    - lib/view/assets/test_user_icon.png
    - lib/view/assets/gym_facilitation.png
  uses-material-design: true
