// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOSHj949KqhXJHKgd5upZF6CVIsgPPDNY',
    appId: '1:198136283431:web:93b238b7b42d636ce92902',
    messagingSenderId: '198136283431',
    projectId: 'boulderapp-cfb41',
    authDomain: 'boulderapp-cfb41.firebaseapp.com',
    storageBucket: 'boulderapp-cfb41.firebasestorage.app',
    measurementId: 'G-EFL56EQ3SR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7mpw3i9ojUaeRi799CGp-EWgWmRSBzQQ',
    appId: '1:198136283431:android:96fe1bfe5c15e8bde92902',
    messagingSenderId: '198136283431',
    projectId: 'boulderapp-cfb41',
    storageBucket: 'boulderapp-cfb41.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKJorw3Ky1tllfCLACtd1R1-UzwQHDc6w',
    appId: '1:198136283431:ios:41f046957a89562be92902',
    messagingSenderId: '198136283431',
    projectId: 'boulderapp-cfb41',
    storageBucket: 'boulderapp-cfb41.firebasestorage.app',
    iosBundleId: 'com.example.boulderingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKJorw3Ky1tllfCLACtd1R1-UzwQHDc6w',
    appId: '1:198136283431:ios:41f046957a89562be92902',
    messagingSenderId: '198136283431',
    projectId: 'boulderapp-cfb41',
    storageBucket: 'boulderapp-cfb41.firebasestorage.app',
    iosBundleId: 'com.example.boulderingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOSHj949KqhXJHKgd5upZF6CVIsgPPDNY',
    appId: '1:198136283431:web:c11f83be93427bade92902',
    messagingSenderId: '198136283431',
    projectId: 'boulderapp-cfb41',
    authDomain: 'boulderapp-cfb41.firebaseapp.com',
    storageBucket: 'boulderapp-cfb41.firebasestorage.app',
    measurementId: 'G-V4G9G98JW7',
  );
}
